package com.zhang.zdg2.model;

import java.util.Date;

public class Account {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.username
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.password
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.role
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.tel
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.real_name
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.credit_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String creditId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.validity_date
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private Date validityDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.emain_adr
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String emainAdr;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.username
	 * @return  the value of account.username
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.username
	 * @param username  the value for account.username
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.password
	 * @return  the value of account.password
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.password
	 * @param password  the value for account.password
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.role
	 * @return  the value of account.role
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.role
	 * @param role  the value for account.role
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.tel
	 * @return  the value of account.tel
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.tel
	 * @param tel  the value for account.tel
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.real_name
	 * @return  the value of account.real_name
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.real_name
	 * @param realName  the value for account.real_name
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.credit_id
	 * @return  the value of account.credit_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getCreditId() {
		return creditId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.credit_id
	 * @param creditId  the value for account.credit_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setCreditId(String creditId) {
		this.creditId = creditId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.id
	 * @return  the value of account.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.id
	 * @param id  the value for account.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.validity_date
	 * @return  the value of account.validity_date
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public Date getValidityDate() {
		return validityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.validity_date
	 * @param validityDate  the value for account.validity_date
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setValidityDate(Date validityDate) {
		this.validityDate = validityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.emain_adr
	 * @return  the value of account.emain_adr
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getEmainAdr() {
		return emainAdr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.emain_adr
	 * @param emainAdr  the value for account.emain_adr
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setEmainAdr(String emainAdr) {
		this.emainAdr = emainAdr;
	}
}