package com.zhang.zdg2.model;

public class Apply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String dgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.dg_price
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private Long dgPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.order_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apply.apply_state
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String applyState;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.dg_id
	 * @return  the value of apply.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getDgId() {
		return dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.dg_id
	 * @param dgId  the value for apply.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setDgId(String dgId) {
		this.dgId = dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.dg_price
	 * @return  the value of apply.dg_price
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public Long getDgPrice() {
		return dgPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.dg_price
	 * @param dgPrice  the value for apply.dg_price
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setDgPrice(Long dgPrice) {
		this.dgPrice = dgPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.order_id
	 * @return  the value of apply.order_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.order_id
	 * @param orderId  the value for apply.order_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apply.apply_state
	 * @return  the value of apply.apply_state
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getApplyState() {
		return applyState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apply.apply_state
	 * @param applyState  the value for apply.apply_state
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setApplyState(String applyState) {
		this.applyState = applyState;
	}
}