package com.zhang.zdg2.model;

import java.util.ArrayList;
import java.util.List;

public class ApplyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public ApplyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDgIdIsNull() {
			addCriterion("dg_id is null");
			return (Criteria) this;
		}

		public Criteria andDgIdIsNotNull() {
			addCriterion("dg_id is not null");
			return (Criteria) this;
		}

		public Criteria andDgIdEqualTo(String value) {
			addCriterion("dg_id =", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotEqualTo(String value) {
			addCriterion("dg_id <>", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdGreaterThan(String value) {
			addCriterion("dg_id >", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdGreaterThanOrEqualTo(String value) {
			addCriterion("dg_id >=", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdLessThan(String value) {
			addCriterion("dg_id <", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdLessThanOrEqualTo(String value) {
			addCriterion("dg_id <=", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdLike(String value) {
			addCriterion("dg_id like", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotLike(String value) {
			addCriterion("dg_id not like", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdIn(List<String> values) {
			addCriterion("dg_id in", values, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotIn(List<String> values) {
			addCriterion("dg_id not in", values, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdBetween(String value1, String value2) {
			addCriterion("dg_id between", value1, value2, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotBetween(String value1, String value2) {
			addCriterion("dg_id not between", value1, value2, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgPriceIsNull() {
			addCriterion("dg_price is null");
			return (Criteria) this;
		}

		public Criteria andDgPriceIsNotNull() {
			addCriterion("dg_price is not null");
			return (Criteria) this;
		}

		public Criteria andDgPriceEqualTo(Long value) {
			addCriterion("dg_price =", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceNotEqualTo(Long value) {
			addCriterion("dg_price <>", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceGreaterThan(Long value) {
			addCriterion("dg_price >", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceGreaterThanOrEqualTo(Long value) {
			addCriterion("dg_price >=", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceLessThan(Long value) {
			addCriterion("dg_price <", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceLessThanOrEqualTo(Long value) {
			addCriterion("dg_price <=", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceIn(List<Long> values) {
			addCriterion("dg_price in", values, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceNotIn(List<Long> values) {
			addCriterion("dg_price not in", values, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceBetween(Long value1, Long value2) {
			addCriterion("dg_price between", value1, value2, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceNotBetween(Long value1, Long value2) {
			addCriterion("dg_price not between", value1, value2, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("order_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("order_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("order_id =", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("order_id <>", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("order_id >", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_id >=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("order_id <", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("order_id <=", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("order_id like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("order_id not like", value, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdIn(List<String> values) {
			addCriterion("order_id in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotIn(List<String> values) {
			addCriterion("order_id not in", values, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("order_id between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("order_id not between", value1, value2, "orderId");
			return (Criteria) this;
		}

		public Criteria andApplyStateIsNull() {
			addCriterion("apply_state is null");
			return (Criteria) this;
		}

		public Criteria andApplyStateIsNotNull() {
			addCriterion("apply_state is not null");
			return (Criteria) this;
		}

		public Criteria andApplyStateEqualTo(String value) {
			addCriterion("apply_state =", value, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateNotEqualTo(String value) {
			addCriterion("apply_state <>", value, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateGreaterThan(String value) {
			addCriterion("apply_state >", value, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateGreaterThanOrEqualTo(String value) {
			addCriterion("apply_state >=", value, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateLessThan(String value) {
			addCriterion("apply_state <", value, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateLessThanOrEqualTo(String value) {
			addCriterion("apply_state <=", value, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateLike(String value) {
			addCriterion("apply_state like", value, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateNotLike(String value) {
			addCriterion("apply_state not like", value, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateIn(List<String> values) {
			addCriterion("apply_state in", values, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateNotIn(List<String> values) {
			addCriterion("apply_state not in", values, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateBetween(String value1, String value2) {
			addCriterion("apply_state between", value1, value2, "applyState");
			return (Criteria) this;
		}

		public Criteria andApplyStateNotBetween(String value1, String value2) {
			addCriterion("apply_state not between", value1, value2, "applyState");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apply
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 09 15:56:54 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}