package com.zhang.zdg2.model;

public class Dgitype {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgitype.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String dgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgitype.type_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String typeId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgitype.dg_id
	 * @return  the value of dgitype.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getDgId() {
		return dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgitype.dg_id
	 * @param dgId  the value for dgitype.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setDgId(String dgId) {
		this.dgId = dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgitype.type_id
	 * @return  the value of dgitype.type_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgitype.type_id
	 * @param typeId  the value for dgitype.type_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}
}