package com.zhang.zdg2.model;

import java.util.Date;

public class Dgorder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.need
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String need;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.order_status
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.open_time
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private Date openTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.demander_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String demanderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String dgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.order_type_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String orderTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.need_street_addr
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String needStreetAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.need_home_addr
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String needHomeAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dgorder.tel
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String tel;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.id
	 * @return  the value of dgorder.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.id
	 * @param id  the value for dgorder.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.need
	 * @return  the value of dgorder.need
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getNeed() {
		return need;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.need
	 * @param need  the value for dgorder.need
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setNeed(String need) {
		this.need = need;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.order_status
	 * @return  the value of dgorder.order_status
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.order_status
	 * @param orderStatus  the value for dgorder.order_status
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.open_time
	 * @return  the value of dgorder.open_time
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public Date getOpenTime() {
		return openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.open_time
	 * @param openTime  the value for dgorder.open_time
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.demander_id
	 * @return  the value of dgorder.demander_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getDemanderId() {
		return demanderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.demander_id
	 * @param demanderId  the value for dgorder.demander_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setDemanderId(String demanderId) {
		this.demanderId = demanderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.dg_id
	 * @return  the value of dgorder.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getDgId() {
		return dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.dg_id
	 * @param dgId  the value for dgorder.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setDgId(String dgId) {
		this.dgId = dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.order_type_id
	 * @return  the value of dgorder.order_type_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getOrderTypeId() {
		return orderTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.order_type_id
	 * @param orderTypeId  the value for dgorder.order_type_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setOrderTypeId(String orderTypeId) {
		this.orderTypeId = orderTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.need_street_addr
	 * @return  the value of dgorder.need_street_addr
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getNeedStreetAddr() {
		return needStreetAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.need_street_addr
	 * @param needStreetAddr  the value for dgorder.need_street_addr
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setNeedStreetAddr(String needStreetAddr) {
		this.needStreetAddr = needStreetAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.need_home_addr
	 * @return  the value of dgorder.need_home_addr
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getNeedHomeAddr() {
		return needHomeAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.need_home_addr
	 * @param needHomeAddr  the value for dgorder.need_home_addr
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setNeedHomeAddr(String needHomeAddr) {
		this.needHomeAddr = needHomeAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dgorder.tel
	 * @return  the value of dgorder.tel
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dgorder.tel
	 * @param tel  the value for dgorder.tel
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}
}