package com.zhang.zdg2.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DgorderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public DgorderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNeedIsNull() {
			addCriterion("need is null");
			return (Criteria) this;
		}

		public Criteria andNeedIsNotNull() {
			addCriterion("need is not null");
			return (Criteria) this;
		}

		public Criteria andNeedEqualTo(String value) {
			addCriterion("need =", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedNotEqualTo(String value) {
			addCriterion("need <>", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedGreaterThan(String value) {
			addCriterion("need >", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedGreaterThanOrEqualTo(String value) {
			addCriterion("need >=", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedLessThan(String value) {
			addCriterion("need <", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedLessThanOrEqualTo(String value) {
			addCriterion("need <=", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedLike(String value) {
			addCriterion("need like", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedNotLike(String value) {
			addCriterion("need not like", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedIn(List<String> values) {
			addCriterion("need in", values, "need");
			return (Criteria) this;
		}

		public Criteria andNeedNotIn(List<String> values) {
			addCriterion("need not in", values, "need");
			return (Criteria) this;
		}

		public Criteria andNeedBetween(String value1, String value2) {
			addCriterion("need between", value1, value2, "need");
			return (Criteria) this;
		}

		public Criteria andNeedNotBetween(String value1, String value2) {
			addCriterion("need not between", value1, value2, "need");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("order_status is null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("order_status is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusEqualTo(String value) {
			addCriterion("order_status =", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotEqualTo(String value) {
			addCriterion("order_status <>", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThan(String value) {
			addCriterion("order_status >", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
			addCriterion("order_status >=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThan(String value) {
			addCriterion("order_status <", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(String value) {
			addCriterion("order_status <=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLike(String value) {
			addCriterion("order_status like", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotLike(String value) {
			addCriterion("order_status not like", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIn(List<String> values) {
			addCriterion("order_status in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotIn(List<String> values) {
			addCriterion("order_status not in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusBetween(String value1, String value2) {
			addCriterion("order_status between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotBetween(String value1, String value2) {
			addCriterion("order_status not between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOpenTimeIsNull() {
			addCriterion("open_time is null");
			return (Criteria) this;
		}

		public Criteria andOpenTimeIsNotNull() {
			addCriterion("open_time is not null");
			return (Criteria) this;
		}

		public Criteria andOpenTimeEqualTo(Date value) {
			addCriterion("open_time =", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeNotEqualTo(Date value) {
			addCriterion("open_time <>", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeGreaterThan(Date value) {
			addCriterion("open_time >", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("open_time >=", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeLessThan(Date value) {
			addCriterion("open_time <", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeLessThanOrEqualTo(Date value) {
			addCriterion("open_time <=", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeIn(List<Date> values) {
			addCriterion("open_time in", values, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeNotIn(List<Date> values) {
			addCriterion("open_time not in", values, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeBetween(Date value1, Date value2) {
			addCriterion("open_time between", value1, value2, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeNotBetween(Date value1, Date value2) {
			addCriterion("open_time not between", value1, value2, "openTime");
			return (Criteria) this;
		}

		public Criteria andDemanderIdIsNull() {
			addCriterion("demander_id is null");
			return (Criteria) this;
		}

		public Criteria andDemanderIdIsNotNull() {
			addCriterion("demander_id is not null");
			return (Criteria) this;
		}

		public Criteria andDemanderIdEqualTo(String value) {
			addCriterion("demander_id =", value, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdNotEqualTo(String value) {
			addCriterion("demander_id <>", value, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdGreaterThan(String value) {
			addCriterion("demander_id >", value, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdGreaterThanOrEqualTo(String value) {
			addCriterion("demander_id >=", value, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdLessThan(String value) {
			addCriterion("demander_id <", value, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdLessThanOrEqualTo(String value) {
			addCriterion("demander_id <=", value, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdLike(String value) {
			addCriterion("demander_id like", value, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdNotLike(String value) {
			addCriterion("demander_id not like", value, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdIn(List<String> values) {
			addCriterion("demander_id in", values, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdNotIn(List<String> values) {
			addCriterion("demander_id not in", values, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdBetween(String value1, String value2) {
			addCriterion("demander_id between", value1, value2, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDemanderIdNotBetween(String value1, String value2) {
			addCriterion("demander_id not between", value1, value2, "demanderId");
			return (Criteria) this;
		}

		public Criteria andDgIdIsNull() {
			addCriterion("dg_id is null");
			return (Criteria) this;
		}

		public Criteria andDgIdIsNotNull() {
			addCriterion("dg_id is not null");
			return (Criteria) this;
		}

		public Criteria andDgIdEqualTo(String value) {
			addCriterion("dg_id =", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotEqualTo(String value) {
			addCriterion("dg_id <>", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdGreaterThan(String value) {
			addCriterion("dg_id >", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdGreaterThanOrEqualTo(String value) {
			addCriterion("dg_id >=", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdLessThan(String value) {
			addCriterion("dg_id <", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdLessThanOrEqualTo(String value) {
			addCriterion("dg_id <=", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdLike(String value) {
			addCriterion("dg_id like", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotLike(String value) {
			addCriterion("dg_id not like", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdIn(List<String> values) {
			addCriterion("dg_id in", values, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotIn(List<String> values) {
			addCriterion("dg_id not in", values, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdBetween(String value1, String value2) {
			addCriterion("dg_id between", value1, value2, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotBetween(String value1, String value2) {
			addCriterion("dg_id not between", value1, value2, "dgId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdIsNull() {
			addCriterion("order_type_id is null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdIsNotNull() {
			addCriterion("order_type_id is not null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdEqualTo(String value) {
			addCriterion("order_type_id =", value, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdNotEqualTo(String value) {
			addCriterion("order_type_id <>", value, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdGreaterThan(String value) {
			addCriterion("order_type_id >", value, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdGreaterThanOrEqualTo(String value) {
			addCriterion("order_type_id >=", value, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdLessThan(String value) {
			addCriterion("order_type_id <", value, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdLessThanOrEqualTo(String value) {
			addCriterion("order_type_id <=", value, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdLike(String value) {
			addCriterion("order_type_id like", value, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdNotLike(String value) {
			addCriterion("order_type_id not like", value, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdIn(List<String> values) {
			addCriterion("order_type_id in", values, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdNotIn(List<String> values) {
			addCriterion("order_type_id not in", values, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdBetween(String value1, String value2) {
			addCriterion("order_type_id between", value1, value2, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIdNotBetween(String value1, String value2) {
			addCriterion("order_type_id not between", value1, value2, "orderTypeId");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrIsNull() {
			addCriterion("need_street_addr is null");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrIsNotNull() {
			addCriterion("need_street_addr is not null");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrEqualTo(String value) {
			addCriterion("need_street_addr =", value, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrNotEqualTo(String value) {
			addCriterion("need_street_addr <>", value, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrGreaterThan(String value) {
			addCriterion("need_street_addr >", value, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrGreaterThanOrEqualTo(String value) {
			addCriterion("need_street_addr >=", value, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrLessThan(String value) {
			addCriterion("need_street_addr <", value, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrLessThanOrEqualTo(String value) {
			addCriterion("need_street_addr <=", value, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrLike(String value) {
			addCriterion("need_street_addr like", value, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrNotLike(String value) {
			addCriterion("need_street_addr not like", value, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrIn(List<String> values) {
			addCriterion("need_street_addr in", values, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrNotIn(List<String> values) {
			addCriterion("need_street_addr not in", values, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrBetween(String value1, String value2) {
			addCriterion("need_street_addr between", value1, value2, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedStreetAddrNotBetween(String value1, String value2) {
			addCriterion("need_street_addr not between", value1, value2, "needStreetAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrIsNull() {
			addCriterion("need_home_addr is null");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrIsNotNull() {
			addCriterion("need_home_addr is not null");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrEqualTo(String value) {
			addCriterion("need_home_addr =", value, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrNotEqualTo(String value) {
			addCriterion("need_home_addr <>", value, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrGreaterThan(String value) {
			addCriterion("need_home_addr >", value, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrGreaterThanOrEqualTo(String value) {
			addCriterion("need_home_addr >=", value, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrLessThan(String value) {
			addCriterion("need_home_addr <", value, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrLessThanOrEqualTo(String value) {
			addCriterion("need_home_addr <=", value, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrLike(String value) {
			addCriterion("need_home_addr like", value, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrNotLike(String value) {
			addCriterion("need_home_addr not like", value, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrIn(List<String> values) {
			addCriterion("need_home_addr in", values, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrNotIn(List<String> values) {
			addCriterion("need_home_addr not in", values, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrBetween(String value1, String value2) {
			addCriterion("need_home_addr between", value1, value2, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andNeedHomeAddrNotBetween(String value1, String value2) {
			addCriterion("need_home_addr not between", value1, value2, "needHomeAddr");
			return (Criteria) this;
		}

		public Criteria andTelIsNull() {
			addCriterion("tel is null");
			return (Criteria) this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("tel is not null");
			return (Criteria) this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("tel =", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("tel <>", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("tel >", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("tel >=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("tel <", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("tel <=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("tel like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("tel not like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelIn(List<String> values) {
			addCriterion("tel in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotIn(List<String> values) {
			addCriterion("tel not in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("tel between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("tel not between", value1, value2, "tel");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dgorder
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 09 15:56:54 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}