package com.zhang.zdg2.model;

import java.math.BigDecimal;

public class Ordertype {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ordertype.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ordertype.name
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ordertype.refer_price
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private BigDecimal referPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ordertype.id
	 * @return  the value of ordertype.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ordertype.id
	 * @param id  the value for ordertype.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ordertype.name
	 * @return  the value of ordertype.name
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ordertype.name
	 * @param name  the value for ordertype.name
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ordertype.refer_price
	 * @return  the value of ordertype.refer_price
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public BigDecimal getReferPrice() {
		return referPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ordertype.refer_price
	 * @param referPrice  the value for ordertype.refer_price
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setReferPrice(BigDecimal referPrice) {
		this.referPrice = referPrice;
	}
}