package com.zhang.zdg2.model;

public class Remark {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column remark.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column remark.lable
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String lable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column remark.comment
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column remark.score
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column remark.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String dgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column remark.demander_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	private String demanderId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column remark.id
	 * @return  the value of remark.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column remark.id
	 * @param id  the value for remark.id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column remark.lable
	 * @return  the value of remark.lable
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getLable() {
		return lable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column remark.lable
	 * @param lable  the value for remark.lable
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setLable(String lable) {
		this.lable = lable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column remark.comment
	 * @return  the value of remark.comment
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column remark.comment
	 * @param comment  the value for remark.comment
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column remark.score
	 * @return  the value of remark.score
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column remark.score
	 * @param score  the value for remark.score
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column remark.dg_id
	 * @return  the value of remark.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getDgId() {
		return dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column remark.dg_id
	 * @param dgId  the value for remark.dg_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setDgId(String dgId) {
		this.dgId = dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column remark.demander_id
	 * @return  the value of remark.demander_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public String getDemanderId() {
		return demanderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column remark.demander_id
	 * @param demanderId  the value for remark.demander_id
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	public void setDemanderId(String demanderId) {
		this.demanderId = demanderId;
	}
}