package com.zhang.zdg2.dao;

import com.zhang.zdg2.model.Apply;
import com.zhang.zdg2.model.ApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	long countByExample(ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int deleteByExample(ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insert(Apply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insertSelective(Apply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	List<Apply> selectByExample(ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Apply record, @Param("example") ApplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apply
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExample(@Param("record") Apply record, @Param("example") ApplyExample example);
}