package com.zhang.zdg2.dao;

import com.zhang.zdg2.model.Dgitype;
import com.zhang.zdg2.model.DgitypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DgitypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgitype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	long countByExample(DgitypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgitype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int deleteByExample(DgitypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgitype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insert(Dgitype record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgitype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insertSelective(Dgitype record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgitype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	List<Dgitype> selectByExample(DgitypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgitype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Dgitype record, @Param("example") DgitypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgitype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExample(@Param("record") Dgitype record, @Param("example") DgitypeExample example);
}