package com.zhang.zdg2.dao;

import com.zhang.zdg2.model.Dgorder;
import com.zhang.zdg2.model.DgorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DgorderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	long countByExample(DgorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int deleteByExample(DgorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insert(Dgorder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insertSelective(Dgorder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	List<Dgorder> selectByExample(DgorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Dgorder record, @Param("example") DgorderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dgorder
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExample(@Param("record") Dgorder record, @Param("example") DgorderExample example);
}