package com.zhang.zdg2.dao;

import com.zhang.zdg2.model.Ordertype;
import com.zhang.zdg2.model.OrdertypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdertypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ordertype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	long countByExample(OrdertypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ordertype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int deleteByExample(OrdertypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ordertype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insert(Ordertype record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ordertype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insertSelective(Ordertype record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ordertype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	List<Ordertype> selectByExample(OrdertypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ordertype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Ordertype record, @Param("example") OrdertypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ordertype
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExample(@Param("record") Ordertype record, @Param("example") OrdertypeExample example);
}