package com.zhang.zdg2.dao;

import com.zhang.zdg2.model.Remark;
import com.zhang.zdg2.model.RemarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RemarkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table remark
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	long countByExample(RemarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table remark
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int deleteByExample(RemarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table remark
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insert(Remark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table remark
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int insertSelective(Remark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table remark
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	List<Remark> selectByExample(RemarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table remark
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Remark record, @Param("example") RemarkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table remark
	 * @mbg.generated  Tue Jul 09 16:50:35 CST 2019
	 */
	int updateByExample(@Param("record") Remark record, @Param("example") RemarkExample example);
}