package com.zhang.zdg1.dao;

import com.zhang.zdg1.model.WireOrder;
import com.zhang.zdg1.model.WireOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WireOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_order
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    long countByExample(WireOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_order
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    int deleteByExample(WireOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_order
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    int insert(WireOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_order
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    int insertSelective(WireOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_order
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    List<WireOrder> selectByExample(WireOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_order
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") WireOrder record, @Param("example") WireOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wire_order
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    int updateByExample(@Param("record") WireOrder record, @Param("example") WireOrderExample example);
}