package com.zhang.zdg1.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public OrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andOpenTimeIsNull() {
			addCriterion("open_time is null");
			return (Criteria) this;
		}

		public Criteria andOpenTimeIsNotNull() {
			addCriterion("open_time is not null");
			return (Criteria) this;
		}

		public Criteria andOpenTimeEqualTo(Date value) {
			addCriterion("open_time =", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeNotEqualTo(Date value) {
			addCriterion("open_time <>", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeGreaterThan(Date value) {
			addCriterion("open_time >", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("open_time >=", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeLessThan(Date value) {
			addCriterion("open_time <", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeLessThanOrEqualTo(Date value) {
			addCriterion("open_time <=", value, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeIn(List<Date> values) {
			addCriterion("open_time in", values, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeNotIn(List<Date> values) {
			addCriterion("open_time not in", values, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeBetween(Date value1, Date value2) {
			addCriterion("open_time between", value1, value2, "openTime");
			return (Criteria) this;
		}

		public Criteria andOpenTimeNotBetween(Date value1, Date value2) {
			addCriterion("open_time not between", value1, value2, "openTime");
			return (Criteria) this;
		}

		public Criteria andNeedIsNull() {
			addCriterion("need is null");
			return (Criteria) this;
		}

		public Criteria andNeedIsNotNull() {
			addCriterion("need is not null");
			return (Criteria) this;
		}

		public Criteria andNeedEqualTo(String value) {
			addCriterion("need =", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedNotEqualTo(String value) {
			addCriterion("need <>", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedGreaterThan(String value) {
			addCriterion("need >", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedGreaterThanOrEqualTo(String value) {
			addCriterion("need >=", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedLessThan(String value) {
			addCriterion("need <", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedLessThanOrEqualTo(String value) {
			addCriterion("need <=", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedLike(String value) {
			addCriterion("need like", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedNotLike(String value) {
			addCriterion("need not like", value, "need");
			return (Criteria) this;
		}

		public Criteria andNeedIn(List<String> values) {
			addCriterion("need in", values, "need");
			return (Criteria) this;
		}

		public Criteria andNeedNotIn(List<String> values) {
			addCriterion("need not in", values, "need");
			return (Criteria) this;
		}

		public Criteria andNeedBetween(String value1, String value2) {
			addCriterion("need between", value1, value2, "need");
			return (Criteria) this;
		}

		public Criteria andNeedNotBetween(String value1, String value2) {
			addCriterion("need not between", value1, value2, "need");
			return (Criteria) this;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNull() {
			addCriterion("order_type is null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIsNotNull() {
			addCriterion("order_type is not null");
			return (Criteria) this;
		}

		public Criteria andOrderTypeEqualTo(String value) {
			addCriterion("order_type =", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotEqualTo(String value) {
			addCriterion("order_type <>", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThan(String value) {
			addCriterion("order_type >", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
			addCriterion("order_type >=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThan(String value) {
			addCriterion("order_type <", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLessThanOrEqualTo(String value) {
			addCriterion("order_type <=", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeLike(String value) {
			addCriterion("order_type like", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotLike(String value) {
			addCriterion("order_type not like", value, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeIn(List<String> values) {
			addCriterion("order_type in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotIn(List<String> values) {
			addCriterion("order_type not in", values, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeBetween(String value1, String value2) {
			addCriterion("order_type between", value1, value2, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderTypeNotBetween(String value1, String value2) {
			addCriterion("order_type not between", value1, value2, "orderType");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("order_status is null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("order_status is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusEqualTo(String value) {
			addCriterion("order_status =", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotEqualTo(String value) {
			addCriterion("order_status <>", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThan(String value) {
			addCriterion("order_status >", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
			addCriterion("order_status >=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThan(String value) {
			addCriterion("order_status <", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(String value) {
			addCriterion("order_status <=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLike(String value) {
			addCriterion("order_status like", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotLike(String value) {
			addCriterion("order_status not like", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIn(List<String> values) {
			addCriterion("order_status in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotIn(List<String> values) {
			addCriterion("order_status not in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusBetween(String value1, String value2) {
			addCriterion("order_status between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotBetween(String value1, String value2) {
			addCriterion("order_status not between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("user_id like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("user_id not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andDgIdIsNull() {
			addCriterion("dg_id is null");
			return (Criteria) this;
		}

		public Criteria andDgIdIsNotNull() {
			addCriterion("dg_id is not null");
			return (Criteria) this;
		}

		public Criteria andDgIdEqualTo(String value) {
			addCriterion("dg_id =", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotEqualTo(String value) {
			addCriterion("dg_id <>", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdGreaterThan(String value) {
			addCriterion("dg_id >", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdGreaterThanOrEqualTo(String value) {
			addCriterion("dg_id >=", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdLessThan(String value) {
			addCriterion("dg_id <", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdLessThanOrEqualTo(String value) {
			addCriterion("dg_id <=", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdLike(String value) {
			addCriterion("dg_id like", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotLike(String value) {
			addCriterion("dg_id not like", value, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdIn(List<String> values) {
			addCriterion("dg_id in", values, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotIn(List<String> values) {
			addCriterion("dg_id not in", values, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdBetween(String value1, String value2) {
			addCriterion("dg_id between", value1, value2, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgIdNotBetween(String value1, String value2) {
			addCriterion("dg_id not between", value1, value2, "dgId");
			return (Criteria) this;
		}

		public Criteria andDgPriceIsNull() {
			addCriterion("dg_price is null");
			return (Criteria) this;
		}

		public Criteria andDgPriceIsNotNull() {
			addCriterion("dg_price is not null");
			return (Criteria) this;
		}

		public Criteria andDgPriceEqualTo(BigDecimal value) {
			addCriterion("dg_price =", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceNotEqualTo(BigDecimal value) {
			addCriterion("dg_price <>", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceGreaterThan(BigDecimal value) {
			addCriterion("dg_price >", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("dg_price >=", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceLessThan(BigDecimal value) {
			addCriterion("dg_price <", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("dg_price <=", value, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceIn(List<BigDecimal> values) {
			addCriterion("dg_price in", values, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceNotIn(List<BigDecimal> values) {
			addCriterion("dg_price not in", values, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("dg_price between", value1, value2, "dgPrice");
			return (Criteria) this;
		}

		public Criteria andDgPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("dg_price not between", value1, value2, "dgPrice");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table order
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 03 17:48:46 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}