package com.zhang.zdg1.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.open_time
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	private Date openTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.need
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	private String need;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.id
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.order_type
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	private String orderType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.order_status
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	private String orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.user_id
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.dg_id
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	private String dgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.dg_price
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	private BigDecimal dgPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.open_time
	 * @return  the value of order.open_time
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public Date getOpenTime() {
		return openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.open_time
	 * @param openTime  the value for order.open_time
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.need
	 * @return  the value of order.need
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public String getNeed() {
		return need;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.need
	 * @param need  the value for order.need
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setNeed(String need) {
		this.need = need;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.id
	 * @return  the value of order.id
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.id
	 * @param id  the value for order.id
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.order_type
	 * @return  the value of order.order_type
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public String getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.order_type
	 * @param orderType  the value for order.order_type
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.order_status
	 * @return  the value of order.order_status
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public String getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.order_status
	 * @param orderStatus  the value for order.order_status
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.user_id
	 * @return  the value of order.user_id
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.user_id
	 * @param userId  the value for order.user_id
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.dg_id
	 * @return  the value of order.dg_id
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public String getDgId() {
		return dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.dg_id
	 * @param dgId  the value for order.dg_id
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setDgId(String dgId) {
		this.dgId = dgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.dg_price
	 * @return  the value of order.dg_price
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public BigDecimal getDgPrice() {
		return dgPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.dg_price
	 * @param dgPrice  the value for order.dg_price
	 * @mbg.generated  Wed Jul 03 17:58:48 CST 2019
	 */
	public void setDgPrice(BigDecimal dgPrice) {
		this.dgPrice = dgPrice;
	}
}