package com.zhang.zdg1.model;

import java.math.BigDecimal;
import java.util.Date;

public class WireOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_order.open_time
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    private Date openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_order.need
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    private String need;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_order.id
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_order.order_type
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_order.order_status
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_order.user_id
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_order.dg_id
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    private Integer dgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wire_order.dg_price
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    private BigDecimal dgPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_order.open_time
     *
     * @return the value of wire_order.open_time
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_order.open_time
     *
     * @param openTime the value for wire_order.open_time
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_order.need
     *
     * @return the value of wire_order.need
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public String getNeed() {
        return need;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_order.need
     *
     * @param need the value for wire_order.need
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public void setNeed(String need) {
        this.need = need;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_order.id
     *
     * @return the value of wire_order.id
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_order.id
     *
     * @param id the value for wire_order.id
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_order.order_type
     *
     * @return the value of wire_order.order_type
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_order.order_type
     *
     * @param orderType the value for wire_order.order_type
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_order.order_status
     *
     * @return the value of wire_order.order_status
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_order.order_status
     *
     * @param orderStatus the value for wire_order.order_status
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_order.user_id
     *
     * @return the value of wire_order.user_id
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_order.user_id
     *
     * @param userId the value for wire_order.user_id
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_order.dg_id
     *
     * @return the value of wire_order.dg_id
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public Integer getDgId() {
        return dgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_order.dg_id
     *
     * @param dgId the value for wire_order.dg_id
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public void setDgId(Integer dgId) {
        this.dgId = dgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wire_order.dg_price
     *
     * @return the value of wire_order.dg_price
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public BigDecimal getDgPrice() {
        return dgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wire_order.dg_price
     *
     * @param dgPrice the value for wire_order.dg_price
     *
     * @mbg.generated Fri Jul 05 16:30:19 CST 2019
     */
    public void setDgPrice(BigDecimal dgPrice) {
        this.dgPrice = dgPrice;
    }
}